#creating a custom exception
class NegativeNumberError(Exception):
  pass
def check_positive(num):
  if num < 0:
    raise NegativeNumberError("negative number entered")
try:
  num = int(input("enter a positive number:"))
  check_positive(num)
  print("you entered a positive number.")
except NegativeNumberError as e:
  print(e)
